//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HourlyLoad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HourlyLoad()
        {
            this.Load = new HashSet<Load>();
        }
    
        public int ID { get; set; }
        public int SemesterNumber { get; set; }
        public Nullable<int> Lection { get; set; }
        public Nullable<int> Practice { get; set; }
        public Nullable<int> LabWork { get; set; }
        public Nullable<int> CourseWork { get; set; }
        public Nullable<int> Consultation { get; set; }
        public Nullable<int> Exam { get; set; }
        public int Summ { get; set; }
        public string Offset { get; set; }
        public int ID_discipline { get; set; }
        public int ID_teacher { get; set; }
    
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Load> Load { get; set; }
    }
}
