//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Load
    {
        public int ID { get; set; }
        public int ID_hourlyLoad { get; set; }
        public int ID_teacher { get; set; }
        public int ID_specialty { get; set; }
        public int ID_group { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Speciality Speciality { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual HourlyLoad HourlyLoad { get; set; }
    }
}
