//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Load_Teacher
    {
        public int ID { get; set; }
        public int Hourly_Load { get; set; }
        public int ID_teacher { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
